### ISSUE TITLE
Improving retainer tracking (3hrs)

### ISSUE THREAD

**Issue by thrillingbillings** [thrillingbillings/thrillingbillings#2]
Improve retainer tracking for accurate reconciliation between Harvest and Quickbooks.

- [x] Understand Harvest retainer process and implications for accounting 

- [x] Work with Shelley to implement retainer tracking in Harvest

- [x] Document new process (1 hr)

- [ ] Troubleshoot problems post-implementation (2 hrs)

**Comment by thrillingbillings** [comment]
<img width="815" alt="Screen Shot 2019-12-30 at 5 23 05 PM" src="https://user-images.githubusercontent.com/37644973/71603207-d840cb80-2b29-11ea-8559-e2b71247e601.png">

**Comment by thrillingbillings** [comment]
Draft documentation can be found here:
https://docs.google.com/document/d/1z-zR5zvyUzcNKr0nuUZBLpTUFQyxFbyzF7w5XjtN-4s/edit#heading=h.g712tj7b3db

**Comment by thrillingbillings** [comment]
Shelly has implemented retainer tracking for new projects.
